version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - rabbitmq_container
    command: python3 main.py
    environment:
      - RABBIT_HOST=rabbitmq_container
  rabbitmq_container:
    image: "rabbitmq:3-management"
    ports:
        - "5672:5672"
        - "15672:15672"
    hostname: rabbitmq_container
  celery_work:
    build: .
    command: celery -A celery_work worker --loglevel=INFO --pool=solo
    depends_on:
      - rabbitmq_container
    environment:
      - RABBIT_HOST=rabbitmq_container
  celery_tasks:
    build: .
    command: celery -A celery_work beat --loglevel=INFO
    depends_on:
      - rabbitmq_container
    environment:
      - RABBIT_HOST=rabbitmq_container